apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
data:
  LOG_LEVEL: "debug"
  BACKEND_RELOAD: "true"
  ENABLE_METRICS: "true"
  ENABLE_TRACING: "false"
  CORS_ORIGINS: "http://localhost:3000,http://localhost:8000"
