{{- if or .Values.frontend.ingress.enabled .Values.backend.ingress.enabled -}}
{{- $fullName := include "todo-app.fullname" . -}}
{{- $ingressApiIsStable := eq (include "todo-app.ingress.isStable" .) "true" -}}
{{- $ingressClassName := "" -}}
{{- if .Values.frontend.ingress.className -}}
{{- $ingressClassName = .Values.frontend.ingress.className -}}
{{- else if .Values.backend.ingress.className -}}
{{- $ingressClassName = .Values.backend.ingress.className -}}
{{- end -}}
{{- if and $ingressApiIsStable (not (empty $ingressClassName)) }}
apiVersion: networking.k8s.io/v1
{{- else if $ingressApiIsStable }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
  {{- with (coalesce .Values.frontend.ingress.annotations .Values.backend.ingress.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and $ingressApiIsStable (not (empty $ingressClassName)) }}
  ingressClassName: {{ $ingressClassName }}
  {{- end }}
  {{- if or .Values.frontend.ingress.tls .Values.backend.ingress.tls }}
  tls:
    {{- range (coalesce .Values.frontend.ingress.tls .Values.backend.ingress.tls) }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.frontend.ingress.enabled }}
    {{- range .Values.frontend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ include "todo-app.frontend.fullname" . }}
                port:
                  number: {{ $.Values.frontend.service.port }}
              {{- else }}
              serviceName: {{ include "todo-app.frontend.fullname" . }}
              servicePort: http
              {{- end }}
          {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.backend.ingress.enabled }}
    {{- range .Values.backend.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              {{- if $ingressApiIsStable }}
              service:
                name: {{ include "todo-app.backend.fullname" . }}
                port:
                  number: {{ $.Values.backend.service.port }}
              {{- else }}
              serviceName: {{ include "todo-app.backend.fullname" . }}
              servicePort: http
              {{- end }}
          {{- end }}
    {{- end }}
    {{- end }}
{{- end }}