replicaCount: 1
services:
  frontend:
    resources:
      requests: { cpu: "50m", memory: "64Mi" }
      limits: { cpu: "250m", memory: "256Mi" }
  backend:
    resources:
      requests: { cpu: "100m", memory: "128Mi" }
      limits: { cpu: "500m", memory: "512Mi" }
global:
  ingress:
    enabled: true
    hosts:
      app: "app.$(minikube ip).nip.io"  # Runtime mein replace karo
      api: "api.$(minikube ip).nip.io"