apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-evolution.fullname" . }}-backend-config
  labels:
    app: backend
data:
  APP_NAME: "Todo Evolution"
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  LOG_LEVEL: "info"
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.global.kafka.bootstrap | quote }}
