apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-frontend-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "todo-chatbot.selectorLabels" . | nindent 4 }}
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.frontend.port }}
      targetPort: 3000
      nodePort: 30080
  type: {{ .Values.service.frontend.type }}